# Generated by Django 5.1.6 on 2025-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_ingredient', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('recipe_cuisine', models.CharField(max_length=30)),
                ('meal_type', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
